# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

haversine_cpp_vec <- function(latFrom, lonFrom, latTo, lonTo, earth_radius) {
    .Call('_spatialrisk_haversine_cpp_vec', PACKAGE = 'spatialrisk', latFrom, lonFrom, latTo, lonTo, earth_radius)
}

haversine_loop_cpp <- function(x, lat_center, lon_center, radius = 200) {
    .Call('_spatialrisk_haversine_loop_cpp', PACKAGE = 'spatialrisk', x, lat_center, lon_center, radius)
}

concentration_loop_cpp <- function(sub, ref, radius = 200, display_progress = TRUE) {
    .Call('_spatialrisk_concentration_loop_cpp', PACKAGE = 'spatialrisk', sub, ref, radius, display_progress)
}

