# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

concentration_loop_cpp <- function(sub, ref, radius = 200, display_progress = TRUE, r = 6378137.0) {
    .Call('_spatialrisk_concentration_loop_cpp', PACKAGE = 'spatialrisk', sub, ref, radius, display_progress, r)
}

block_loop_cpp <- function(sub, ref, radius = 200) {
    .Call('_spatialrisk_block_loop_cpp', PACKAGE = 'spatialrisk', sub, ref, radius)
}

concentration_loop_xy_cpp <- function(sub, ref, radius = 200) {
    .Call('_spatialrisk_concentration_loop_xy_cpp', PACKAGE = 'spatialrisk', sub, ref, radius)
}

concentration_loop_cpp2 <- function(sub, ref, radius = 200) {
    .Call('_spatialrisk_concentration_loop_cpp2', PACKAGE = 'spatialrisk', sub, ref, radius)
}

indexed_concentration_best_cpp <- function(x_candidates, y_candidates, x_ref, y_ref, value_ref, ix_ref, radius, cell_width) {
    .Call('_spatialrisk_indexed_concentration_best_cpp', PACKAGE = 'spatialrisk', x_candidates, y_candidates, x_ref, y_ref, value_ref, ix_ref, radius, cell_width)
}

indexed_points_in_radius_cpp <- function(x_center, y_center, x_ref, y_ref, value_ref, ix_ref, radius, cell_width) {
    .Call('_spatialrisk_indexed_points_in_radius_cpp', PACKAGE = 'spatialrisk', x_center, y_center, x_ref, y_ref, value_ref, ix_ref, radius, cell_width)
}

pair_intersection_best_cpp <- function(x_ref, y_ref, value_ref, ix_ref, radius, cell_width) {
    .Call('_spatialrisk_pair_intersection_best_cpp', PACKAGE = 'spatialrisk', x_ref, y_ref, value_ref, ix_ref, radius, cell_width)
}

haversine_cpp_vec <- function(lat_from, lon_from, lat_to, lon_to, r) {
    .Call('_spatialrisk_haversine_cpp_vec', PACKAGE = 'spatialrisk', lat_from, lon_from, lat_to, lon_to, r)
}

haversine_cpp <- function(lat_from, lon_from, lat_to, lon_to, r = 6378137.0) {
    .Call('_spatialrisk_haversine_cpp', PACKAGE = 'spatialrisk', lat_from, lon_from, lat_to, lon_to, r)
}

add_cell_bounds_cpp <- function(df, size = 50, radius = 200) {
    .Call('_spatialrisk_add_cell_bounds_cpp', PACKAGE = 'spatialrisk', df, size, radius)
}

expand_grid_cpp <- function(seq1, seq2) {
    .Call('_spatialrisk_expand_grid_cpp', PACKAGE = 'spatialrisk', seq1, seq2)
}

filter_full_cpp <- function(dffull, subb, i) {
    .Call('_spatialrisk_filter_full_cpp', PACKAGE = 'spatialrisk', dffull, subb, i)
}

max_conc_per_cell_cpp <- function(dfsub, dffull, points = 50L, size = 50, radius = 200, r = 6378137.0) {
    .Call('_spatialrisk_max_conc_per_cell_cpp', PACKAGE = 'spatialrisk', dfsub, dffull, points, size, radius, r)
}

points_in_radius_cpp <- function(x, lat_center, lon_center, radius = 200, r = 6378137.0) {
    .Call('_spatialrisk_points_in_radius_cpp', PACKAGE = 'spatialrisk', x, lat_center, lon_center, radius, r)
}

points_in_radius_multi_cpp <- function(x, lat_centers, lon_centers, radius = 200, r = 6378137.0) {
    .Call('_spatialrisk_points_in_radius_multi_cpp', PACKAGE = 'spatialrisk', x, lat_centers, lon_centers, radius, r)
}

haversine_loop_cpp0 <- function(x, lat_centers, lon_centers, radius = 200) {
    .Call('_spatialrisk_haversine_loop_cpp0', PACKAGE = 'spatialrisk', x, lat_centers, lon_centers, radius)
}

one_lon_in_meters <- function(lat0) {
    .Call('_spatialrisk_one_lon_in_meters', PACKAGE = 'spatialrisk', lat0)
}

seq_cpp <- function(from, to, length_out) {
    .Call('_spatialrisk_seq_cpp', PACKAGE = 'spatialrisk', from, to, length_out)
}

highest_indices_cpp <- function(x, n) {
    .Call('_spatialrisk_highest_indices_cpp', PACKAGE = 'spatialrisk', x, n)
}

